### PR TITLE
Ruby-capstone: Develop

### PR DESCRIPTION
**Pull request by omarbabou**
**Added Changes**: 

- [ ] Created a User Interface for the application
- [ ] Added and Implemented: All methods are visible in the diagram.
- [ ] Created a schema.sql file with tables that will be analogical to the structure of the classes in your app.
- [ ] Added Tests for all methods.
- [ ] Correct linters error.

[Video Demo](https://www.loom.com/share/a1bc9af978e34eb08ba7d7160e3251da)

### CODE REVIEW

**Review by mirouhml — CHANGES_REQUESTED** [review]
Hi @omarbabou, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

**Please know that you're the only participant in a group project, I also checked the video and found no one else, I am not sure if you didn't get assigned with anyone in your group project or something of the sort, for that reason I will invalidate this review request, but please before submitting again explain in your pull request why you're alone in a group project and with proof if you have no coding partners so that we can see what to do in this case.**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by omarbabou** [comment]
Hello @mirouhml 
Hope you're doing good 

I would like to inform you that am solo for this project. I don't have any partner. 
Here is the screenshot attached
 
Screen Shot 2022-10-26 at 11 55 51

**Comment by mirouhml** [comment]
Hello @omarbabou thanks for confirming just go ahead and submit the project again another reviewer should claim this shortly!

**Comment by omarbabou** [comment]
Hello @mirouhml Thank you

**Review by ShoiraTa — APPROVED** [review]
### **STATUS: APPROVED  ✔️** 
------
Hi @omarbabou ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍 
- Project is set up correctly ✔️ 
- All the functionality works as expected  ✔️ 
- Descriptive Pull Request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 


image

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@shoirata] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.


***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
